#!/usr/bin/python2.7
from hosted import device, node, config, time, threading
config.restart_on_update()

device.gpio.monitor(config.pin_16)
device.gpio.monitor(config.pin_17)
device.gpio.monitor(config.pin_18)
device.gpio.monitor(config.pin_19)

def handle_pin(pin, state):
    if state == 1:
        print(f"pin {pin} touched")
        node.send(f'/state/{pin}:1')
        time.sleep(20)  # Adjust the sleep time as needed

def gpio_poll_loop():
    for pin, state in device.gpio.poll_forever():
        if pin in [16, 17, 18, 19]:
            threading.Thread(target=handle_pin, args=(pin, state)).start()

# Start the GPIO polling loop in a separate thread
gpio_poll_thread = threading.Thread(target=gpio_poll_loop)
gpio_poll_thread.start()
